### PR TITLE
MIST-572 Make tests pass

### PR DESCRIPTION
**Pull request by TauZero**
[Review on Reviewable](https://reviewable.io/reviews/mistifyio/lochness/118)

### CODE REVIEW

**Comment by TauZero** [comment]
Ok to test

**Comment by TauZero** [comment]
Ok to test

**Comment by mmlb** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[pkg/lock/lock_test.go, line 26 \[r2\]](https://reviewable.io:443/reviews/mistifyio/lochness/118#-JyspuVZa8-yTYn1xncz)** ([raw file](https://github.com/mistifyio/lochness/blob/b4ae3b578353eef38b497ad904df2e30cfb6f048/pkg/lock/lock_test.go#L26)):</sup>
Was this causing any error, or just a bit of confusion?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/118)

**Comment by TauZero** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[pkg/lock/lock_test.go, line 26 \[r2\]](https://reviewable.io:443/reviews/mistifyio/lochness/118#-JyspuVZa8-yTYn1xncz)** ([raw file](https://github.com/mistifyio/lochness/blob/b4ae3b578353eef38b497ad904df2e30cfb6f048/pkg/lock/lock_test.go#L26)):</sup>
Mostly confusion. "Is kv the key or the value or both?" Splitting the uuid bit off also makes it more realistic; in practice the key is the part that shouldn't vary (i.e. a key "restarting-etcd") while the value should be the unique bit to the thing trying to gain the lock (i.e. node UUID).

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/118)

**Pull request merged**
