### PR TITLE
MIST-561 Cleanup for linting, etc.

### PR DESCRIPTION
**Pull request by TauZero**
Some changes related to cleanup in mistify-agent

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/lochness/117)

### CODE REVIEW

**Comment by mmlb** [comment]
Reviewed 2 of 2 files at r1, 2 of 2 files at r2, 4 of 4 files at r3, 9 of 9 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[cmd/cdhcpd/main.go, line 158 \[r3\]](https://reviewable.io:443/reviews/mistifyio/lochness/117#-JyhuEljKQ22BzwI22Vn)** ([raw file](https://github.com/mistifyio/lochness/blob/6072389fd56ad4d6a61d1935cb49ba1e43f2d93d/cmd/cdhcpd/main.go#L158)):</sup>
ughh this annoys me slightly... :(

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/117)

**Comment by TauZero** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[cmd/cdhcpd/main.go, line 158 \[r3\]](https://reviewable.io:443/reviews/mistifyio/lochness/117#-JyhuEljKQ22BzwI22Vn)** ([raw file](https://github.com/mistifyio/lochness/blob/6072389fd56ad4d6a61d1935cb49ba1e43f2d93d/cmd/cdhcpd/main.go#L158)):</sup>
Would you be better with `restartDHCPd`?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/117)

**Comment by mmlb** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[cmd/cdhcpd/main.go, line 163 \[r3\]](https://reviewable.io:443/reviews/mistifyio/lochness/117#-JyhuEljKQ22BzwI22Vn)** ([raw file](https://github.com/mistifyio/lochness/blob/6072389fd56ad4d6a61d1935cb49ba1e43f2d93d/cmd/cdhcpd/main.go#L163)):</sup>
no, my preferred name would be restart_dhcpd, since in this case we are not talking about dhcp the acronym. And that would mean treating golint as a warning in ci (which we should probably do anyway), but not in this case. Its not that big of a deal.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/117)

**Comment by TauZero** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[cmd/cdhcpd/main.go, line 158 \[r3\]](https://reviewable.io:443/reviews/mistifyio/lochness/117#-JyhuEljKQ22BzwI22Vn)** ([raw file](https://github.com/mistifyio/lochness/blob/6072389fd56ad4d6a61d1935cb49ba1e43f2d93d/cmd/cdhcpd/main.go#L158)):</sup>
I'd rather be consistent with either camelCase or snake_case, and the convention in go is camelCase.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/117)

**Comment by TauZero** [comment]
Ok to test

**Comment by TauZero** [comment]
Ok to test

**Comment by TauZero** [comment]
Ok to test

**Comment by TauZero** [comment]
Ok to test

**Comment by TauZero** [comment]
Ok to test

**Comment by TauZero** [comment]
Ok to test

**Comment by TauZero** [comment]
Subsequent PR's should fix the tests. This first PR was primarily for linting. Merging.

**Pull request merged**
