### PR TITLE
Add consul implementation to pkg/kv

### LINKED ISSUE #133: add consul implementation of pkg/kv/kv and switch to it
# Description
tbd

# Related Issues
#122 - abstract kv use into a package

### PR DESCRIPTION
**Pull request by mmlb**
fixes #133

---

This change is [Reviewable](https://reviewable.io/reviews/mistifyio/lochness/134)

### CODE REVIEW

**Comment by TauZero** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, 4 of 4 files at r8, 4 of 4 files at r9, 1 of 1 files at r10, 1 of 1 files at r11, 7 of 7 files at r12, 1 of 1 files at r13, 3 of 3 files at r14, 1 of 1 files at r15, 3 of 3 files at r16, 1 of 1 files at r17, 3 of 3 files at r18, 16 of 16 files at r19, 19 of 19 files at r20.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmd/nheartbeatd/main.go, line 23 \[r7\]](https://reviewable.io:443/reviews/mistifyio/lochness/134#-KFAFEAHenZOF3PnIjBa:-KFAFEAHenZOF3PnIjBb:1431116381) ([raw file](https://github.com/mistifyio/lochness/blob/c88dfe5d8e1a4e6b763cfc654ee5303028748446/cmd/nheartbeatd/main.go#L23)):*
I thought `flag.Visit` loops through all of the flags. Wouldn't this always set `intervalSet` to true since there's a flag named "interval"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistifyio/lochness/134)*

**Comment by mmlb** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmd/nheartbeatd/main.go, line 23 \[r7\]](https://reviewable.io:443/reviews/mistifyio/lochness/134#-KFAFEAHenZOF3PnIjBa:-KFBcHmuIQxaEU5q_uA7:171279664) ([raw file](https://github.com/mistifyio/lochness/blob/c88dfe5d8e1a4e6b763cfc654ee5303028748446/cmd/nheartbeatd/main.go#L23)):*
`flag.Visit` will loop through all of the args provided on the cli.

```Visit visits the command-line flags in lexicographical order, calling fn for each. It visits only those flags that have been set.```

It could do with better wording, but my manual testing confirms. `flag.VisitAll` will be called for all _defined_ args.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistifyio/lochness/134)*

**Comment by TauZero** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cmd/nheartbeatd/main.go, line 23 \[r7\]](https://reviewable.io:443/reviews/mistifyio/lochness/134#-KFAFEAHenZOF3PnIjBa:-KFF6NUuQbYjzX7QswqH:569913210) ([raw file](https://github.com/mistifyio/lochness/blob/c88dfe5d8e1a4e6b763cfc654ee5303028748446/cmd/nheartbeatd/main.go#L23)):*
Interesting. Could have sworn that wasn't the case. I remember some StackOverflow questions about trying to get whether the flag value was provided or defaulted. If your testing shows it works as you expect,  :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistifyio/lochness/134)*

**Comment by mmlb** [comment]
well that travis was unexpected

**Comment by TauZero** [comment]
Reviewed 10 of 10 files at r21.
Review status: 47 of 49 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/kv/kv.go, line 23 \[r21\]](https://reviewable.io:443/reviews/mistifyio/lochness/134#-KGOHoetjtX9dZkagTDg:-KGOHoeuNIeYyd3XiTnb:1873753822) ([raw file](https://github.com/mistifyio/lochness/blob/8d0ac371b7142ca1370b3e86bcfa8ab8551a4f21/pkg/kv/kv.go#L23)):*
You're going to want to change this either now, or at least when we import into `cerana/cerana` so that it doesn't use the stupid underscore-prefixed and snake case names, like we had to do for `zfs`. Something like

```
go:generate sh -c "stringer -type=EventType && sed -i 's#_EventType_name#eventTypeName#g;s#_EventType_index#eventTypeIndex#g' eventtype_string.go"
```

Probably easier just to do it now since it's new.

---

*[pkg/kv/kv_test.go, line 30 \[r21\]](https://reviewable.io:443/reviews/mistifyio/lochness/134#-KGOI1zT4-upHCQzsWfK:-KGOI1zT4-upHCQzsWfL:159553543) ([raw file](https://github.com/mistifyio/lochness/blob/8d0ac371b7142ca1370b3e86bcfa8ab8551a4f21/pkg/kv/kv_test.go#L30)):*
Is this supposed to be empty for the blank and consul case?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistifyio/lochness/134)*

**Comment by TauZero** [comment]
Reviewed 2 of 2 files at r22.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mistifyio/lochness/134)*

**Comment by mmlb** [comment]
Review status: 47 of 49 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/kv/kv.go, line 23 \[r21\]](https://reviewable.io:443/reviews/mistifyio/lochness/134#-KGOHoetjtX9dZkagTDg:-KGSMTlrHiRYbNbr6s8I:-499146009) ([raw file](https://github.com/mistifyio/lochness/blob/8d0ac371b7142ca1370b3e86bcfa8ab8551a4f21/pkg/kv/kv.go#L23)):*
Done.

---

*[pkg/kv/kv_test.go, line 30 \[r21\]](https://reviewable.io:443/reviews/mistifyio/lochness/134#-KGOI1zT4-upHCQzsWfK:-KGSIPdEMKU55piQxpr0:1117841358) ([raw file](https://github.com/mistifyio/lochness/blob/8d0ac371b7142ca1370b3e86bcfa8ab8551a4f21/pkg/kv/kv_test.go#L30)):*
yes the default Maker is ConsulMaker and is setup in `internal/tests/common/ct.go:106`. I wanted to protect against an unknown `KV` env var.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/mistifyio/lochness/134)*

**Comment by TauZero** [comment]
Reviewed 2 of 2 files at r23.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mistifyio/lochness/134)*

**Pull request merged**
