### PR TITLE
move common_test

### PR DESCRIPTION
**Pull request by mmlb**
[Review on Reviewable](https://reviewable.io/reviews/mistifyio/lochness/124)

### CODE REVIEW

**Comment by TauZero** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 30 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/124)*

**Comment by TauZero** [comment]
Review status: 0 of 30 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/nfirewalld/main_test.go, line 52 \[r2\]](https://reviewable.io:443/reviews/mistifyio/lochness/124#-KApv_94cckicLpTOZ3K:-KApv_94cckicLpTOZ3L:-2096372146) ([raw file](https://github.com/mistifyio/lochness/blob/10d41df3fd7da8a72d539f1f926a6148f5389b3e/cmd/nfirewalld/main_test.go#L52)):*
Needs a `t.SkipNow()` so it's still skipped

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/124)*

**Comment by TauZero** [comment]
Reviewed 11 of 22 files at r3.
Review status: 0 of 30 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/124)*

**Comment by TauZero** [comment]
Reviewed 1 of 1 files at r4, 30 of 42 files at r5, 1 of 1 files at r9.
Review status: 3 of 30 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/cbootstrapd/api_test.go, line 22 \[r9\]](https://reviewable.io:443/reviews/mistifyio/lochness/124#-KApx0mcL4TWK_ilr99c:-KApx0mcL4TWK_ilr99d:423163084) ([raw file](https://github.com/mistifyio/lochness/blob/d48eaa7c2f83cc7a89147ac22b8f11cd1590deef/cmd/cbootstrapd/api_test.go#L22)):*
I think this is too vague. Maybe `FooSuite` as a compromise. Similarly for the other suites

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/124)*

**Comment by mmlb** [comment]
Review status: 2 of 30 files reviewed at latest revision, 2 unresolved discussions.

---

*[cmd/cbootstrapd/api_test.go, line 22 \[r9\]](https://reviewable.io:443/reviews/mistifyio/lochness/124#-KApx0mcL4TWK_ilr99c:-KAq61Hy6S_MzFs0aocA:-499146009) ([raw file](https://github.com/mistifyio/lochness/blob/d48eaa7c2f83cc7a89147ac22b8f11cd1590deef/cmd/cbootstrapd/api_test.go#L22)):*
Done.

---

*[cmd/nfirewalld/cmd_test.go, line 52 \[r2\]](https://reviewable.io:443/reviews/mistifyio/lochness/124#-KApv_94cckicLpTOZ3K:-KAq63QAOxI7qZLogUof:-499146009) ([raw file](https://github.com/mistifyio/lochness/blob/10d41df3fd7da8a72d539f1f926a6148f5389b3e/cmd/nfirewalld/cmd_test.go#L52)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/124)*

**Comment by TauZero** [comment]
Reviewed 1 of 3 files at r2, 3 of 48 files at r5, 3 of 43 files at r7, 24 of 24 files at r8, 18 of 19 files at r10, 1 of 1 files at r11.
Review status: 22 of 30 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/124)*

**Comment by TauZero** [comment]
Reviewed 3 of 19 files at r10, 7 of 8 files at r12, 1 of 1 files at r13.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/124)*

**Comment by TauZero** [comment]
Reviewed 2 of 3 files at r14, 1 of 1 files at r15.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/124)*

**Pull request merged**
