### PR TITLE
MIST-589 Test all the things

### PR DESCRIPTION
**Pull request by TauZero**
Tests for lochness, the sub packages, internal packages, and commands.  A small handful of commands were left out of testing due to how thin they were (e.g. cli tools that are just wrappers) or very difficult testing.

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/lochness/121)

### CODE REVIEW

**Comment by TauZero** [comment]
Ok to test

**Comment by mmlb** [comment]
Reviewed 87 of 87 files at r1.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---

*[cmd/common_test/cmd.go, line 19 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9V-SLL3YgMGX1xmFQF:-K9V-SLL3YgMGX1xmFQG:-1761055888) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/cmd/common_test/cmd.go#L19)):*
This is a misleading name, exec in the unix world has a very well defined behavior mainly that this process's memory is replaced with the exec'ed one, which is not at all what is going on here. Why not `Start`? It actually matches the stdlib term and what you are doing too.

---

*[cmd/common_test/ct.go, line 39 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9UpgEZNELR81agFhcJ:-K9UpgEZNELR81agFhcK:-1681784080) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/cmd/common_test/ct.go#L39)):*
delete

---

*[cmd/common_test/ct.go, line 68 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9UpeCzUGEu4y0_HlSH:-K9UpeCzUGEu4y0_HlSI:-1681784080) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/cmd/common_test/ct.go#L68)):*
delete

---

*[cmd/common_test/ct.go, line 120 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9UqHBbQQDXxAh69YQa:-K9UqHBbQQDXxAh69YQb:-427504162) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/cmd/common_test/ct.go#L120)):*
what's special about 4066?

---

*[cmd/common_test/README.md, line 3 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9Uy0OGQXLPM-E6OTMs:-K9Uy0OGQXLPM-E6OTMt:1486407715) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/cmd/common_test/README.md#L3)):*
I have a few nits with this package.

1. Can we move `common_test` out of cmd dir? This makes `go intall github.com/mistifyio/lochness/...` pollute `$GOPATH/bin` with non-useful binaries. We could possibly move to something like `lochness/test/common`.

2. -The New{Guest,Hypervisor,...} functions seem to have a bunch of overlap with `lochness/testhelper` func that `cdhcpd` uses. We should probably merge them.- (kept comment for reference)

3. I kind of alluded to it in 1, but having a package name not match the dir name is a bit of a go nono, either name the dir `ct` or rename the package `common_test`, I think `lochness/test/common` is nice because then the funcs would be `common.TestSuite` and `foo.TestSuite.SetupSuite()` for example, seems nicer.

4. Also since all the package tests are not part of the package maybe we should move to `tests/lochness`? This will cut down on the number of files in first dir that new people will have to look at.

---

*[cmd/common_test/README.md, line 9 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9V07gMZRJq9BZffoQ9:-K9V07gN8bp5cyiFssZH:-985174421) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/cmd/common_test/README.md#L9)):*
hmm I wonder if this README is in need of regeneration? Aren't the godoc comments supposed to show up here too? So it seems that the template's `{{ if not .IsCommand }}` is matching this as a command and therefore not generating the usage info. That seems like a bug in godocdown to me.

---

*[cmd/cworkerd/main.go, line 30 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9V1Azj1Kyk6hygH-vU:-K9V1Azj1Kyk6hygH-vV:1118419584) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/cmd/cworkerd/main.go#L30)):*
Man I really hate it when tool defaults aren't really specified and I have to go digging for it. I think you should just replace `0` with the actual default or at least document it in the help message.

---

*[common_test.go, line 29 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9V40YKoctIfnEbRnJS:-K9V40YKoctIfnEbRnJT:-1681784080) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/common_test.go#L29)):*
delete

---

*[common_test.go, line 77 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9V49KHgu8H8XWVavlb:-K9V49KHgu8H8XWVavlc:272928920) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/common_test.go#L77)):*
???? I'm confused, why is this and the others below here when we also have `PrefixKey`?

---

*[config.go, line 52 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9UoEa0TrZk-JmeVP5F:-K9UoEa0TrZk-JmeVP5G:-210542507) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/config.go#L52)):*
There is enough similarity with `Context.ForEachConfig` that maybe they should be merged or share a sub-function?

---

*[hypervisor.go, line 311 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9V5fPYXnf4N1Uc5doK:-K9V5fPYXnf4N1Uc5doL:1862950695) ([raw file](https://github.com/mistifyio/lochness/blob/03e0eae96254b79339580d5dc0ae99dfb20aae92/hypervisor.go#L311)):*
gutes wtf?

---

*[hypervisor_test.go, line 200 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9YPOzQBlbTr4DpMo2t:-K9YPOzRHRhve4S15eY2:1730760690) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/hypervisor_test.go#L200)):*
You can collapse these 2 lines into just
```
clobberHypervisor := *goodHypervisor
```

or even just use `*goodHypervisor` directly in the table/test def.

---

*[hypervisor_test.go, line 354 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9YQo02RjkVFdWpiTMS:-K9YQo02RjkVFdWpiTMT:452109424) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/hypervisor_test.go#L354)):*
rename to `guest1`?

---

*[network_test.go, line 103 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9YmICRIxVIJv9c0TaM:-K9YmICRIxVIJv9c0TaN:510474628) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/network_test.go#L103)):*
can do the same as in hypervisor testszn

---

*[pkg/deferer/deferer.go, line 84 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9YmUjj2xd9z4R7v5EW:-K9YmUjj2xd9z4R7v5EX:780942676) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/pkg/deferer/deferer.go#L84)):*
this is redundant

---

*[pkg/jobqueue/README.md, line 97 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9YnhFJeKw_MEsmxZ9k:-K9YnhFJeKw_MEsmxZ9l:-1889122752) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/pkg/jobqueue/README.md#L97)):*
typo in source?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/121)*

**Comment by mmlb** [comment]
Reviewed 1 of 1 files at r2, 2 of 3 files at r3, 11 of 22 files at r4, 1 of 1 files at r5, 31 of 48 files at r6, 24 of 41 files at r7, 6 of 12 files at r8, 15 of 37 files at r9, 24 of 24 files at r10, 1 of 1 files at r11.
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/121)*

**Comment by TauZero** [comment]
Reviewed 1 of 37 files at r9, 1 of 1 files at r11.
Review status: 85 of 89 files reviewed at latest revision, 15 unresolved discussions.

---

*[cmd/cworkerd/main.go, line 30 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9V1Azj1Kyk6hygH-vU:-KAqEaAF0JVl5vmGrlXq:-499146009) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/cmd/cworkerd/main.go#L30)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/121)*

**Comment by TauZero** [comment]
Review status: 74 of 89 files reviewed at latest revision, 15 unresolved discussions.

---

*[config.go, line 52 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9UoEa0TrZk-JmeVP5F:-KAqI4PMvfngh_epKkSO:-434947653) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/config.go#L52)):*
`Context.ForEachConfig` calls this

---

*[internal/tests/common/cmd.go, line 19 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9V-SLL3YgMGX1xmFQF:-KAqLmSQ-zlr5aKGhBYK:1755713581) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/internal/tests/common/cmd.go#L19)):*
Renamed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/121)*

**Comment by TauZero** [comment]
Review status: 72 of 89 files reviewed at latest revision, 15 unresolved discussions.

---

*[internal/tests/common/ct.go, line 39 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9UpgEZNELR81agFhcJ:-KAqMqzrK_R5v4rB91So:-499146009) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/internal/tests/common/ct.go#L39)):*
Done.

---

*[internal/tests/common/ct.go, line 68 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9UpeCzUGEu4y0_HlSH:-KAqMvVl_11hfGE5SDHn:-499146009) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/internal/tests/common/ct.go#L68)):*
Done.

---

*[internal/tests/common/ct.go, line 120 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9UqHBbQQDXxAh69YQa:-KAqNNCjEngF-VAH1dvj:-17700918) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/internal/tests/common/ct.go#L120)):*
Was supposed to be 4096. 12 bits are used for tagging.

---

*[internal/tests/common/README.md, line 3 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9Uy0OGQXLPM-E6OTMs:-KAqNkEVRLKltPp5Os6f:437311475) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/internal/tests/common/README.md#L3)):*
Manny seems to have covered 1, 3, 4.  The 2 was taken care of with the removal of testhelper

---

*[internal/tests/common/README.md, line 9 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9V07gMZRJq9BZffoQ9:-KAqPVKncXNA4Q2teN_E:-499146009) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/internal/tests/common/README.md#L9)):*
Done.

---

*[internal/tests/lochness/hypervisor_test.go, line 200 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9YPOzQBlbTr4DpMo2t:-KAqQKf6fwIFOYXzRqEp:735624965) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/internal/tests/lochness/hypervisor_test.go#L200)):*
Done. Can't use `*goodHypervisor` directly since the copy needs to be made before saving it (which happens in the previous test case)

---

*[internal/tests/lochness/hypervisor_test.go, line 354 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9YQo02RjkVFdWpiTMS:-KAqRTd2Mq-nmxOsN2NY:-499146009) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/internal/tests/lochness/hypervisor_test.go#L354)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/121)*

**Comment by TauZero** [comment]
Review status: 72 of 89 files reviewed at latest revision, 15 unresolved discussions.

---

*[internal/tests/lochness/network_test.go, line 103 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9YmICRIxVIJv9c0TaM:-KAqSdDQOOAC8IZYsiot:-499146009) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/internal/tests/lochness/network_test.go#L103)):*
Done.

---

*[pkg/deferer/deferer.go, line 84 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9YmUjj2xd9z4R7v5EW:-KAqTx8O3hlAgX8Ci_kD:-499146009) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/pkg/deferer/deferer.go#L84)):*
Done.

---

*[pkg/jobqueue/README.md, line 97 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9YnhFJeKw_MEsmxZ9k:-KAqUBT_mPFrsRKQcjB_:-499146009) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/pkg/jobqueue/README.md#L97)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/121)*

**Comment by mmlb** [comment]
Reviewed 1 of 3 files at r3, 3 of 48 files at r6, 6 of 12 files at r8, 1 of 24 files at r10, 4 of 4 files at r12, 9 of 9 files at r13, 4 of 4 files at r14, 1 of 1 files at r15, 1 of 1 files at r16, 1 of 1 files at r17.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/jobqueue/README.md, line 97 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9YnhFJeKw_MEsmxZ9k:-KAqXTEk7zNWttfJCLYh:-1771783377) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/pkg/jobqueue/README.md#L97)):*
Not seeing it changed here, still have `create create` :/

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/121)*

**Comment by TauZero** [comment]
Review status: 80 of 89 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/jobqueue/README.md, line 97 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/121#-K9YnhFJeKw_MEsmxZ9k:-KAqa_NR1Non1dD4YjX0:-568860763) ([raw file](https://github.com/mistifyio/lochness/blob/cfc7ab40462bcad803103f725b0a60f2cd3b25f4/pkg/jobqueue/README.md#L97)):*
Pushing the change would have helped...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/121)*

**Comment by mmlb** [comment]
Reviewed 6 of 24 files at r10, 6 of 6 files at r18, 1 of 1 files at r19, 2 of 2 files at r20.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/121)*

**Comment by TauZero** [comment]
Ok to test

**Comment by TauZero** [comment]
Ok to test

**Comment by TauZero** [comment]
Ok to test

**Comment by mmlb** [comment]
Reviewed 1 of 3 files at r3, 6 of 12 files at r8, 24 of 24 files at r21, 22 of 22 files at r22, 33 of 33 files at r23, 2 of 2 files at r24.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/121)*

**Pull request merged**
