### PR TITLE
MIST-456 Add hostport package

### PR DESCRIPTION
**Pull request by TauZero**
[Review on Reviewable](https://reviewable.io/reviews/mistifyio/lochness/106)

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/mistifyio/lochness/pull/106" target="_blank">ReviewNinja

**Comment by mmlb** [comment]
Lets add some tests to this. The link you shared is a pretty good start I'd say. Remove the net.HostPort comparison and maybe format it as an Example instead of a Test so that it shows up in docs too.

---

Review status: 0 of 2 files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[pkg/hostport/main.go, line 2 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/106#-JqWXkTHze6wc85H71cT)** ([raw file](https://github.com/mistifyio/lochness/blob/1c83e2c8d8b1b2ff581ec27222767146528c216d/pkg/hostport/main.go#L2)):</sup>
/networks/network

---

<sup>**[pkg/hostport/main.go, line 14 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/106#-JqWXqPqZL8w7HDKtYBx)** ([raw file](https://github.com/mistifyio/lochness/blob/1c83e2c8d8b1b2ff581ec27222767146528c216d/pkg/hostport/main.go#L14)):</sup>
too many "

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/106)

**Comment by TauZero** [comment]
Review status: 0 of 2 files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[pkg/hostport/main.go, line 2 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/106#-JqWXkTHze6wc85H71cT)** ([raw file](https://github.com/mistifyio/lochness/blob/1c83e2c8d8b1b2ff581ec27222767146528c216d/pkg/hostport/main.go#L2)):</sup>
Done.

---

<sup>**[pkg/hostport/main.go, line 14 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/106#-JqWXqPqZL8w7HDKtYBx)** ([raw file](https://github.com/mistifyio/lochness/blob/1c83e2c8d8b1b2ff581ec27222767146528c216d/pkg/hostport/main.go#L14)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/106)

**Comment by trisk** [comment]
Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.
Reviewed files:
- pkg/hostport/main.go @ r2
- pkg/hostport/README.md @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/106)

**Comment by mmlb** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- pkg/hostport/example_test.go @ r3
- pkg/hostport/hostport.go @ r3
- pkg/hostport/main.go @ r3
- pkg/hostport/README.md @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/106)

**Pull request merged**
