### PR TITLE
MIST-467 img command

### PR DESCRIPTION
**Pull request by TauZero**
Command for interacting with the mistify-image-service
Related to https://github.com/mistifyio/mistify-image-service/pull/6

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/lochness/107)

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/mistifyio/lochness/pull/107" target="_blank">ReviewNinja

**Comment by mmlb** [comment]
Review status: all files reviewed, 8 unresolved discussions, all commit checks successful.
Reviewed files:
- cmd/img/.gitignore @ r1
- cmd/img/doc.go @ r1
- cmd/img/main.go @ r1
- cmd/img/README.md @ r1
- pkg/internal/cli/client.go @ r1
- pkg/internal/cli/README.md @ r1

---

<sup>**[cmd/img/doc.go, line 16 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/107#-JrU3IYwgt_zPngFIze1)** ([raw file](https://github.com/mistifyio/lochness/blob/3d18b7f0990e5373f915435cfbd54ffb401056fe/cmd/img/doc.go#L16)):</sup>
hmmm, maybe should be import instead? fetch is pretty synonymous with download

---

<sup>**[cmd/img/doc.go, line 30 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/107#-JrU1o0MBivozE6SlcYQ)** ([raw file](https://github.com/mistifyio/lochness/blob/3d18b7f0990e5373f915435cfbd54ffb401056fe/cmd/img/doc.go#L30)):</sup>
Async actions queue a job and return the job id(s), the status of which can be checked with the job sub command. btw which job command?

---

<sup>**[cmd/img/doc.go, line 76 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/107#-JrU2J2AOQaK6RPl74Bf)** ([raw file](https://github.com/mistifyio/lochness/blob/3d18b7f0990e5373f915435cfbd54ffb401056fe/cmd/img/doc.go#L76)):</sup>
get rid of the `-s :20000` confused me, made me think that what was being shown not the delete right after.

---

<sup>**[cmd/img/main.go, line 70 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/107#-JrU3XvIhJPwpzzXlk_M)** ([raw file](https://github.com/mistifyio/lochness/blob/3d18b7f0990e5373f915435cfbd54ffb401056fe/cmd/img/main.go#L70)):</sup>
see above

---

<sup>**[cmd/img/main.go, line 113 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/107#-JrU4jghikE5LnEqUP6v)** ([raw file](https://github.com/mistifyio/lochness/blob/3d18b7f0990e5373f915435cfbd54ffb401056fe/cmd/img/main.go#L113)):</sup>
hmm so this wont get called until function returns, until then the file is opened and consuming resources. I don't think it'll be a problem but maybe a comment is worth having.

---

<sup>**[cmd/img/main.go, line 124 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/107#-JrU4Juzskp6b9Dt8LZm)** ([raw file](https://github.com/mistifyio/lochness/blob/3d18b7f0990e5373f915435cfbd54ffb401056fe/cmd/img/main.go#L124)):</sup>
this should come out of loop

---

<sup>**[cmd/img/main.go, line 160 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/107#-JrU8F_zZope4IdibEda)** ([raw file](https://github.com/mistifyio/lochness/blob/3d18b7f0990e5373f915435cfbd54ffb401056fe/cmd/img/main.go#L160)):</sup>
instead of "" for the tempdir, use `downloadDir` which avoids a few errors when renaming later on.

---

<sup>**[cmd/img/main.go, line 260 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/107#-JrU91ZXQ53pHSKWwmeI)** ([raw file](https://github.com/mistifyio/lochness/blob/3d18b7f0990e5373f915435cfbd54ffb401056fe/cmd/img/main.go#L260)):</sup>
We should probably extract this into a package to do this for us, maybe move hostport.Split into it and call it netutil similar to ioutil?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/107)

**Comment by TauZero** [comment]
Review status: 4 of 6 files reviewed, 8 unresolved discussions, all commit checks successful.

---

<sup>**[cmd/img/doc.go, line 16 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/107#-JrU3IYwgt_zPngFIze1)** ([raw file](https://github.com/mistifyio/lochness/blob/3d18b7f0990e5373f915435cfbd54ffb401056fe/cmd/img/doc.go#L16)):</sup>
I was keeping it similar to the wording used inside the `mistify-image-service`, which has fetch and upload for getting images into the service and download for getting them out.

---

<sup>**[cmd/img/doc.go, line 30 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/107#-JrU1o0MBivozE6SlcYQ)** ([raw file](https://github.com/mistifyio/lochness/blob/3d18b7f0990e5373f915435cfbd54ffb401056fe/cmd/img/doc.go#L30)):</sup>
Whoops, accidentally copy/pasted wrong. Fixed.

---

<sup>**[cmd/img/doc.go, line 76 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/107#-JrU2J2AOQaK6RPl74Bf)** ([raw file](https://github.com/mistifyio/lochness/blob/3d18b7f0990e5373f915435cfbd54ffb401056fe/cmd/img/doc.go#L76)):</sup>
Fixed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/107)

**Comment by mmlb** [comment]
Review status: all files reviewed, 6 unresolved discussions, all commit checks successful.
Reviewed files:
- cmd/img/doc.go @ r2
- cmd/img/README.md @ r2

---

<sup>**[cmd/img/doc.go, line 16 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/107#-JrU3IYwgt_zPngFIze1)** ([raw file](https://github.com/mistifyio/lochness/blob/3d18b7f0990e5373f915435cfbd54ffb401056fe/cmd/img/doc.go#L16)):</sup>
yeah, I though of ping'ing you on slack on this but figured since this the user facing view it would be best to start here and update mistify-image-service later.

Alternatively, we can add a new card to rename both in one go.

All this assuming you agree import > fetch, otherwise nop.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/107)

**Comment by TauZero** [comment]
Review status: all files reviewed, 5 unresolved discussions, all commit checks successful.

---

<sup>**[cmd/img/doc.go, line 16 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/107#-JrU3IYwgt_zPngFIze1)** ([raw file](https://github.com/mistifyio/lochness/blob/3d18b7f0990e5373f915435cfbd54ffb401056fe/cmd/img/doc.go#L16)):</sup>
If we do rename, I'd like to do both in one go in another card. Not sure if i like import as it doesn't really distinguish itself from upload; we want a name that indicates it's getting the image from somewhere else.

---

<sup>**[cmd/img/main.go, line 113 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/107#-JrU4jghikE5LnEqUP6v)** ([raw file](https://github.com/mistifyio/lochness/blob/3d18b7f0990e5373f915435cfbd54ffb401056fe/cmd/img/main.go#L113)):</sup>
Added a comment that the file remains open until function exit

---

<sup>**[cmd/img/main.go, line 124 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/107#-JrU4Juzskp6b9Dt8LZm)** ([raw file](https://github.com/mistifyio/lochness/blob/3d18b7f0990e5373f915435cfbd54ffb401056fe/cmd/img/main.go#L124)):</sup>
Fixed.

---

<sup>**[cmd/img/main.go, line 160 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/107#-JrU8F_zZope4IdibEda)** ([raw file](https://github.com/mistifyio/lochness/blob/3d18b7f0990e5373f915435cfbd54ffb401056fe/cmd/img/main.go#L160)):</sup>
What errors are you anticipating renaming from the os default temp dir to the final dir, `downloadDir`?

---

<sup>**[cmd/img/main.go, line 260 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/107#-JrU91ZXQ53pHSKWwmeI)** ([raw file](https://github.com/mistifyio/lochness/blob/3d18b7f0990e5373f915435cfbd54ffb401056fe/cmd/img/main.go#L260)):</sup>
I'll get a card in. We can change everywhere this is used in one card.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/107)

**Comment by mmlb** [comment]
Review status: all files reviewed, 1 unresolved discussion, all commit checks successful.
Reviewed files:
- cmd/img/main.go @ r3

---

<sup>**[cmd/img/doc.go, line 16 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/107#-JrU3IYwgt_zPngFIze1)** ([raw file](https://github.com/mistifyio/lochness/blob/3d18b7f0990e5373f915435cfbd54ffb401056fe/cmd/img/doc.go#L16)):</sup>
Hmm, yeah I see your thoughts on `import`. Seems to me that the other commands are named from the user POV, so fetch and download are more similar than import and upload.

---

<sup>**[cmd/img/main.go, line 160 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/107#-JrU8F_zZope4IdibEda)** ([raw file](https://github.com/mistifyio/lochness/blob/3d18b7f0990e5373f915435cfbd54ffb401056fe/cmd/img/main.go#L160)):</sup>
well in posix systems rename will not work across mount points. So if `TempFile("", ...)` chooses /tmp, which now a days is likely a tmpfs, and dest is $HOME/blah then Rename fails. The solution is to copy the contents. That's the most glaring error I can think of, others may exist.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/107)

**Comment by TauZero** [comment]
Review status: all files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[cmd/img/doc.go, line 16 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/107#-JrU3IYwgt_zPngFIze1)** ([raw file](https://github.com/mistifyio/lochness/blob/3d18b7f0990e5373f915435cfbd54ffb401056fe/cmd/img/doc.go#L16)):</sup>
Hmm. true. We should revisit the naming for both in another card.

---

<sup>**[cmd/img/main.go, line 161 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/107#-JrU8F_zZope4IdibEda)** ([raw file](https://github.com/mistifyio/lochness/blob/3d18b7f0990e5373f915435cfbd54ffb401056fe/cmd/img/main.go#L161)):</sup>
Gotcha. Fixed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/107)

**Comment by mmlb** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- cmd/img/main.go @ r4

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/107)

**Pull request merged**
