### PR TITLE
[WIP] consul

### LINKED ISSUE #122: Convert from etcd to consul
Swap out etcd for consul in lochness.

### PR DESCRIPTION
**Pull request by mmlb**
Will transfer pkg/kv/* to mistifyio/mistify, but leaving here for now facilitates review/test

Still have a couple of issues with consul tests, everything else should stay the same so I wanted to get this review started.

fixes #122

---
This change is [Review on Reviewable](https://reviewable.io/reviews/mistifyio/lochness/129)

### CODE REVIEW

**Comment by TauZero** [comment]
Reviewed 5 of 88 files at r1.
Review status: 5 of 88 files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/129)*

**Comment by TauZero** [comment]
Reviewed 6 of 88 files at r1.
Review status: 11 of 88 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/watcher/watcher_test.go, line 50 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KCWP_QoAvkkWJC53H0K:-KCWP_Qpw1Y1VFHO1_2f:1642542706) ([raw file](https://github.com/mistifyio/lochness/blob/c26e30532d083f943a69a9307e451e2b012e3e5a/pkg/watcher/watcher_test.go#L50)):*
Careful with just sleeping here. Times can vary wildly depending on test env (e.g. sometimes running in Jenkins would take half a second to start up). Perhaps we want a `kv.Ping()` to check for aliveness that can be used in various circumstances rather than waiting and finding out when the first real command fails.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/129)*

**Comment by TauZero** [comment]
Reviewed 6 of 88 files at r1.
Review status: 16 of 88 files reviewed at latest revision, 4 unresolved discussions.

---

*[internal/tests/common/ct.go, line 55 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KCWT2Ywm0OErWKXp77G:-KCWT2Ywm0OErWKXp77H:-580691669) ([raw file](https://github.com/mistifyio/lochness/blob/c26e30532d083f943a69a9307e451e2b012e3e5a/internal/tests/common/ct.go#L55)):*
See my comment on Watcher tests about Sleep.

---

*[pkg/jobqueue/common_test.go, line 47 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KCWSR9iQIyd8fzXrrSU:-KCWSR9iQIyd8fzXrrSV:1532977063) ([raw file](https://github.com/mistifyio/lochness/blob/c26e30532d083f943a69a9307e451e2b012e3e5a/pkg/jobqueue/common_test.go#L47)):*
See my comment on the Watcher test about Sleep.

---

*[pkg/jobqueue/job.go, line 93 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KCWSej--8ufmRk5JB8-:-KCWSej--8ufmRk5JB80:-1718017099) ([raw file](https://github.com/mistifyio/lochness/blob/c26e30532d083f943a69a9307e451e2b012e3e5a/pkg/jobqueue/job.go#L93)):*
Handle this TODO

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/129)*

**Comment by TauZero** [comment]
Reviewed 13 of 88 files at r1.
Review status: 28 of 88 files reviewed at latest revision, 7 unresolved discussions.

---

*[hypervisor.go, line 200 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KCWVZ42RDcrsqvCUyFi:-KCWVZ42RDcrsqvCUyFj:-1967210963) ([raw file](https://github.com/mistifyio/lochness/blob/c26e30532d083f943a69a9307e451e2b012e3e5a/hypervisor.go#L200)):*
Is this still an open TODO?

---

*[vlangroup.go, line 209 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KCWWViCp5Lqjgv0rkEk:-KCWWViCp5Lqjgv0rkEl:-1681037097) ([raw file](https://github.com/mistifyio/lochness/blob/c26e30532d083f943a69a9307e451e2b012e3e5a/vlangroup.go#L209)):*
Open TODO

---

*[pkg/kv/etcd/etcd.go, line 8 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KCWTxoycP7eaHiqiiIW:-KCWTxoycP7eaHiqiiIX:833421571) ([raw file](https://github.com/mistifyio/lochness/blob/c26e30532d083f943a69a9307e451e2b012e3e5a/pkg/kv/etcd/etcd.go#L8)):*
Perhaps it would be a good time to use the newer, non-deprecated etcd client: https://github.com/coreos/etcd/tree/master/client ?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/129)*

**Comment by TauZero** [comment]
Reviewed 16 of 88 files at r1.
Review status: 44 of 88 files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/129)*

**Comment by mmlb** [comment]
Review status: 43 of 88 files reviewed at latest revision, 7 unresolved discussions.

---

*[hypervisor.go, line 200 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KCWVZ42RDcrsqvCUyFi:-KCWvwwL2uGhtOqqHxEw:-1712318160) ([raw file](https://github.com/mistifyio/lochness/blob/c26e30532d083f943a69a9307e451e2b012e3e5a/hypervisor.go#L200)):*
kinda, I'll expand the comment

---

*[vlangroup.go, line 209 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KCWWViCp5Lqjgv0rkEk:-KCWw7xmscTqbJ_h6mJA:-1484119809) ([raw file](https://github.com/mistifyio/lochness/blob/c26e30532d083f943a69a9307e451e2b012e3e5a/vlangroup.go#L209)):*
TODOs sans (mm) are old, I'll take a look and see about expanding the comment/adding an issue

---

*[pkg/kv/etcd/etcd.go, line 8 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KCWTxoycP7eaHiqiiIW:-KCWv_mQHUXUYrpNBy26:1610560562) ([raw file](https://github.com/mistifyio/lochness/blob/c26e30532d083f943a69a9307e451e2b012e3e5a/pkg/kv/etcd/etcd.go#L8)):*
hmm I'll take a look

---

*[pkg/watcher/watcher_test.go, line 50 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KCWP_QoAvkkWJC53H0K:-KCWvlwrs_5Jqk9_cjl4:1727068629) ([raw file](https://github.com/mistifyio/lochness/blob/c26e30532d083f943a69a9307e451e2b012e3e5a/pkg/watcher/watcher_test.go#L50)):*
hmm yeah `Ping()` sounds like a great idea.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/129)*

**Comment by TauZero** [comment]
Reviewed 32 of 88 files at r1.
Review status: 80 of 88 files reviewed at latest revision, 8 unresolved discussions.

---

*[cmd/nheartbeatd/cmd_test.go, line 83 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KCX-MyHF2IeEYWUfcIJ:-KCX-MyIS0Bduqg3Q8mQ:2064019295) ([raw file](https://github.com/mistifyio/lochness/blob/c26e30532d083f943a69a9307e451e2b012e3e5a/cmd/nheartbeatd/cmd_test.go#L83)):*
Open TODO on ttls

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/129)*

**Comment by TauZero** [comment]
Reviewed 1 of 88 files at r1, 41 of 41 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[pkg/jobqueue/task_test.go, line 37 \[r2\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KDU3Da_GCvnGldjfZR_:-KDU3Dab_vQMO3jdD8t0:-24698913) ([raw file](https://github.com/mistifyio/lochness/blob/c9ce0a0b508314ce19958545dd0dc3e17a0c0328/pkg/jobqueue/task_test.go#L37)):*
Don't forget about this.

---

*[pkg/kv/kv.go, line 28 \[r2\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KDU3ZPGuO841CfbTVVW:-KDU3ZPH2zo_P61nZdJ8:-1975429259) ([raw file](https://github.com/mistifyio/lochness/blob/c9ce0a0b508314ce19958545dd0dc3e17a0c0328/pkg/kv/kv.go#L28)):*
Commented out here and in the `types` map.

---

*[pkg/kv/etcd/etcd.go, line 22 \[r2\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KDU3n348doO3X4wbhmO:-KDU3n348doO3X4wbhmP:1022438864) ([raw file](https://github.com/mistifyio/lochness/blob/c9ce0a0b508314ce19958545dd0dc3e17a0c0328/pkg/kv/etcd/etcd.go#L22)):*
Should be `etcd` not `consul` here

---

*[pkg/kv/etcd/README.md, line 14 \[r2\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KDU5DljRblwfkI52rJE:-KDU5Dlk1aByopIQvP-X:145179142) ([raw file](https://github.com/mistifyio/lochness/blob/c9ce0a0b508314ce19958545dd0dc3e17a0c0328/pkg/kv/etcd/README.md#L14)):*
Regenerate this after fixing comment to swap `consul` for `etcd`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/129)*

**Comment by mmlb** [comment]
Review status: 96 of 102 files reviewed at latest revision, 10 unresolved discussions.

---

*[hypervisor.go, line 200 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KCWVZ42RDcrsqvCUyFi:-KDUgYaIEM7Zxnr1XXkS:-499146009) ([raw file](https://github.com/mistifyio/lochness/blob/c26e30532d083f943a69a9307e451e2b012e3e5a/hypervisor.go#L200)):*
Done.

---

*[cmd/nheartbeatd/cmd_test.go, line 83 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KCX-MyHF2IeEYWUfcIJ:-KDTlfRXZGPCmih_ZALe:-499146009) ([raw file](https://github.com/mistifyio/lochness/blob/c26e30532d083f943a69a9307e451e2b012e3e5a/cmd/nheartbeatd/cmd_test.go#L83)):*
Done.

---

*[pkg/jobqueue/job.go, line 93 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KCWSej--8ufmRk5JB8-:-KDTm0NUYLUToFhO3yrK:-499146009) ([raw file](https://github.com/mistifyio/lochness/blob/c26e30532d083f943a69a9307e451e2b012e3e5a/pkg/jobqueue/job.go#L93)):*
Done.

---

*[pkg/jobqueue/task_test.go, line 37 \[r2\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KDU3Da_GCvnGldjfZR_:-KDUfiBSuqmjyK07x732:-943923888) ([raw file](https://github.com/mistifyio/lochness/blob/c9ce0a0b508314ce19958545dd0dc3e17a0c0328/pkg/jobqueue/task_test.go#L37)):*
that was actually there to prompt discussion with you

---

*[pkg/kv/kv.go, line 28 \[r2\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KDU3ZPGuO841CfbTVVW:-KDUfuM4Mk2fKjtAbZOX:-499146009) ([raw file](https://github.com/mistifyio/lochness/blob/c9ce0a0b508314ce19958545dd0dc3e17a0c0328/pkg/kv/kv.go#L28)):*
Done.

---

*[pkg/kv/etcd/etcd.go, line 8 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KCWTxoycP7eaHiqiiIW:-KDUga6uE7YWAAKlwy7p:-1884963555) ([raw file](https://github.com/mistifyio/lochness/blob/c26e30532d083f943a69a9307e451e2b012e3e5a/pkg/kv/etcd/etcd.go#L8)):*
Not going to implement since its a bit of an api difference. A big difference is the use of context.Context which would be nice, but consul does not support and it be a big thing to have to shoe-horn in. May want to do it any way, but not at this time.

---

*[pkg/kv/etcd/etcd.go, line 22 \[r2\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KDU3n348doO3X4wbhmO:-KDUfvXpeYtstaFUETuy:-499146009) ([raw file](https://github.com/mistifyio/lochness/blob/c9ce0a0b508314ce19958545dd0dc3e17a0c0328/pkg/kv/etcd/etcd.go#L22)):*
Done.

---

*[pkg/kv/etcd/README.md, line 14 \[r2\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KDU5DljRblwfkI52rJE:-KDUfxGFUiAvF5P91w1O:-499146009) ([raw file](https://github.com/mistifyio/lochness/blob/c9ce0a0b508314ce19958545dd0dc3e17a0c0328/pkg/kv/etcd/README.md#L14)):*
Done.

---

*[pkg/watcher/watcher_test.go, line 50 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KCWP_QoAvkkWJC53H0K:-KCbwrF_Zo0N0hEzdBMR:1090871193) ([raw file](https://github.com/mistifyio/lochness/blob/c26e30532d083f943a69a9307e451e2b012e3e5a/pkg/watcher/watcher_test.go#L50)):*
Actually no,`Ping()` here would conflict with how `kv.New` is setup to work. `kv.New` will iterate through all the registered implementors trying each successively. An implementor should try to connect to the cluster, and if it can't it should return a nil `kv.KV` w/o an error so that `kv.New` can try the next one.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/129)*

**Comment by mmlb** [comment]
Review status: 96 of 102 files reviewed at latest revision, 10 unresolved discussions.

---

*[internal/tests/common/ct.go, line 55 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KCWT2Ywm0OErWKXp77G:-KDUhAdK1vYXYRrg4SIl:1381271272) ([raw file](https://github.com/mistifyio/lochness/blob/c26e30532d083f943a69a9307e451e2b012e3e5a/internal/tests/common/ct.go#L55)):*
Done...? We can continue conversation there.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/129)*

**Comment by TauZero** [comment]
Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/kv/etcd/etcd.go, line 8 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KCWTxoycP7eaHiqiiIW:-KDUioQ0h8HlPG7pxoot:2060063625) ([raw file](https://github.com/mistifyio/lochness/blob/c26e30532d083f943a69a9307e451e2b012e3e5a/pkg/kv/etcd/etcd.go#L8)):*
Open up an issue to switch. If we're going to maintain an etcd implementation, it'd be nice to use the current one.

---

*[pkg/watcher/watcher_test.go, line 50 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KCWP_QoAvkkWJC53H0K:-KDUj_oKVjAEbMQujZlC:-346668459) ([raw file](https://github.com/mistifyio/lochness/blob/c26e30532d083f943a69a9307e451e2b012e3e5a/pkg/watcher/watcher_test.go#L50)):*
This is fine now, as `s.Suite.SetupSuite()` does a loop on `Ping()` via `kv.New`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/129)*

**Comment by TauZero** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/jobqueue/task_test.go, line 37 \[r2\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KDU3Da_GCvnGldjfZR_:-KDUl3VisIPRa9eY86vs:-603842028) ([raw file](https://github.com/mistifyio/lochness/blob/c9ce0a0b508314ce19958545dd0dc3e17a0c0328/pkg/jobqueue/task_test.go#L37)):*
I'm not sure what the problem is exactly.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/129)*

**Comment by mmlb** [comment]
Review status: 101 of 102 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/jobqueue/task_test.go, line 37 \[r2\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KDU3Da_GCvnGldjfZR_:-KDUs2t0KsbsjGvKRKTd:1776491724) ([raw file](https://github.com/mistifyio/lochness/blob/c9ce0a0b508314ce19958545dd0dc3e17a0c0328/pkg/jobqueue/task_test.go#L37)):*
nm. I thought it was going to be relatively pointless, but it is worth checking for correctness.

---

*[pkg/kv/etcd/etcd.go, line 8 \[r1\]](https://reviewable.io:443/reviews/mistifyio/lochness/129#-KCWTxoycP7eaHiqiiIW:-KDUshmC0q6UioLEviQY:-499146009) ([raw file](https://github.com/mistifyio/lochness/blob/c26e30532d083f943a69a9307e451e2b012e3e5a/pkg/kv/etcd/etcd.go#L8)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/129)*

**Comment by TauZero** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/129)*

**Comment by TauZero** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/lochness/129)*

**Pull request merged**
